---
- name: Apache Installation
  hosts: localhost
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest
- name: Tomcat Process
  hosts: localhost
  sudo: no
  tasks:
    - name: Getting Tomcat files from S3
      command: wget https://s3.amazonaws.com/test1-tomcat/tomcat.tar.gz
    - name: Extract Tomcat 
      command: tar -xvf tomcat.tar.gz
    - name: Modifying .bashrc for CATALINA_HOME
      lineinfile:
       dest: ~/.bashrc
       line: export CATALINA_HOME=/home/ubuntu/opt/tomcat
    - name: Get War file from S3
      command: chdir=/home/ubuntu/opt/tomcat/webapps wget https://s3.amazonaws.com/test1-tomcat/sample.war
    - name: Get War file from S3
      command: chdir=/home/ubuntu/opt/tomcat-7/webapps wget https://s3.amazonaws.com/test1-tomcat/sample.war
- name: Install MySQL for production ready server
  hosts: localhost
  user: root
  sudo: yes 
  vars:
    MySQL_root_pass: Root123#
  tasks:
    - name: Set MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password' value='{{MySQL_root_pass | quote}}' vtype='password'
    - name: Confirm MySQL root password before installing
      debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{MySQL_root_pass | quote}}' vtype='password'
    - name: Install MySQL
      apt: package={{ item }} state=installed force=yes update_cache=yes cache_valid_time=3600
      when: ansible_os_family == 'Debian'
      with_items:
        - mysql-server
        - mysql-client
        - python-mysqldb
